name: rainroot
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  http: ^0.13.4
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  flutter_svg_provider: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Work Sans
      fonts: 
        - asset: assets/fonts/WorkSansRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/WorkSansRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/WorkSansRomanSemiBold.ttf
          weight: 600
    - family: Comfortaa
      fonts: 
        - asset: assets/fonts/ComfortaaRegular.ttf
          weight: 400
        - asset: assets/fonts/ComfortaaBold.ttf
          weight: 700
